// Auto-generated from the FY2025-26 CF296 and CF18 source files on 2026-07-16.
// Index 0 = Cell 1, etc. These map CDSS's generic 'Cell N' columns to their real meanings.
// CF296 has been stable in this cell layout across recent fiscal years per CDSS's report form;
// if a future year's file has a different number of Cell columns, INGEST_CF296 will log a
// warning rather than silently mis-mapping columns (see Utils.gs: assertLabelCountMatches_).

var CF296_LABELS = [
  "PART A. APPLICATIONS FOR CALFRESH | 1. Applications received during the month | TOTAL",
  "PART A. APPLICATIONS FOR CALFRESH | 1.a. Online applications received during the month | TOTAL",
  "PART A. APPLICATIONS FOR CALFRESH | 2. Applications disposed of during the month | TOTAL",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a. Applications approved | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a. Applications approved | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a. Applications approved | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a.1) Applications approved in over 30 days (CWD caused) | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a.1) Applications approved in over 30 days (CWD caused) | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.a.1) Applications approved in over 30 days (CWD caused) | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b. Applications denied | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b. Applications denied | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b. Applications denied | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.1) Applications denied because determined ineligible | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.1) Applications denied because determined ineligible | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.1) Applications denied because determined ineligible | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.2) Applications denied for procedural reasons | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.2) Applications denied for procedural reasons | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.2) Applications denied for procedural reasons | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.3) Applications denied in over 30 days (CWD caused) | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.3) Applications denied in over 30 days (CWD caused) | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.b.3) Applications denied in over 30 days (CWD caused) | TOTAL (C)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.c. Applications withdrawn | PACF (A)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.c. Applications withdrawn | NACF (B)",
  "PART A. APPLICATIONS FOR CALFRESH | 2.c. Applications withdrawn | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under ES | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under ES | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under ES | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a. Found entitled to ES | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a. Found entitled to ES | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a. Found entitled to ES | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.1) Benefits issued in 1-3 days | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.1) Benefits issued in 1-3 days | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.1) Benefits issued in 1-3 days | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.2) Benefits issued in 4-7 days | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.2) Benefits issued in 4-7 days | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.2) Benefits issued in 4-7 days | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.3) Benefits issued in over 7 days | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.3) Benefits issued in over 7 days | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.a.3) Benefits issued in over 7 days | TOTAL (C)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.b. Found not entitled to ES | PACF (A)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.b. Found not entitled to ES | NACF (B)",
  "PART B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3.b. Found not entitled to ES | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.a. Item 8 from last month's report, as reported to CDSS | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.a. Item 8 from last month's report, as reported to CDSS | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.a. Item 8 from last month's report, as reported to CDSS | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.b. Adjustment | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.b. Adjustment | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 4.b. Adjustment | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | PACF | Federal",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | PACF | Fed/State",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | PACF | State",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | NACF | Federal",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | NACF | Fed/State",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | NACF | State",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a. Applications approved | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a.1) Of those applications approved in Item 5a, those approved Overdue Applications with federal funding (derived from Cells 55, 56, 58, 59) | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a.1)I. 1-30 days | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a.1)II. 31-60 days | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a.1)III. 61-90 days | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.a.1)IV. 91+days | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.b. Change in assistance status from PACF or NACF | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.b. Change in assistance status from PACF or NACF | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.b. Change in assistance status from PACF or NACF | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.c. Inter-County Transfers | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.c. Inter-County Transfers | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.c. Inter-County Transfers | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.d. Cases with eligibility reinstated and benefits pro-rated during the month | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.d. Cases with eligibility reinstated and benefits pro-rated during the month | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.d. Cases with eligibility reinstated and benefits pro-rated during the month | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.e. Other approvals | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.e. Other approvals | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 5.e. Other approvals | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month (Certified eligible to participate during the month) | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month (Certified eligible to participate during the month) | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month (Certified eligible to participate during the month) | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.a. Pure federal cases | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.a. Pure federal cases | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.a. Pure federal cases | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.a.1) Federal persons in Item 6a cases plus federal persons in Item 6b cases",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.b. Federal/State combined cases | State Persons | Singles",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.b. Federal/State combined cases | State Persons | Families",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.b. Federal/State combined cases | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.b. Federal/State combined cases | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.b. Federal/State combined cases | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.c. Pure state cases | State Persons | Singles",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.c. Pure state cases | State Persons | Families",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.c. Pure state cases | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.c. Pure state cases | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 6.c. Pure state cases | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7.a. Households discontinued due to recipient failure to complete application process for ongoing benefits (ES only) | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7.a. Households discontinued due to recipient failure to complete application process for ongoing benefits (ES only) | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 7.a. Households discontinued due to recipient failure to complete application process for ongoing benefits (ES only) | TOTAL (C)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | PACF (A)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | NACF (B)",
  "PART C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | PACF (A)",
  "PART D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | NACF (B)",
  "PART D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | PACF | Federal",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | PACF | Fed/State",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | PACF | State",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | NACF | Federal",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | NACF | Fed/State",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | NACF | State",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | PACF (A)",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | NACF (B)",
  "PART D. RECERTIFICATIONS | 9.a. Determined continuing eligible | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a.1) Of the recertifications from Item 9a, those approved Overdue recertifications with federal funding (derived from Cells 110, 111, 113, 114) | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a.1)I. 1-30 days | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a.1)II. 31-60 days | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a.1)III. 61-90 days | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.a.1)IV. 91+days | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | PACF | Federal",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | PACF | Fed/State",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | PACF | State",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | NACF | Federal",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | NACF | Fed/State",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | NACF | State",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | PACF (A)",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | NACF (B)",
  "PART D. RECERTIFICATIONS | 9.b. Determined ineligible | TOTAL (C)",
  "PART D. RECERTIFICATIONS | 10. Overdue recertifications (CWD caused) during the month | PACF (A)",
  "PART D. RECERTIFICATIONS | 10. Overdue recertifications (CWD caused) during the month | NACF (B)",
  "PART D. RECERTIFICATIONS | 10. Overdue recertifications (CWD caused) during the month | TOTAL (C)"
];

var CF18_LABELS = [
  "All SAR 7s & RRRs | 1. The total number of CalFresh and CFAP households scheduled for SAR 7 & RRR submission within the Data Cohort Month | SAR 7",
  "All SAR 7s & RRRs | 1. The total number of CalFresh and CFAP households scheduled for SAR 7 & RRR submission within the Data Cohort Month | RRR",
  "Timely SAR 7s & RRRs | 2. The total number of timely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed eligible | SAR 7",
  "Timely SAR 7s & RRRs | 2. The total number of timely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed eligible | RRR",
  "Timely SAR 7s & RRRs | 3. The total number of timely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed ineligible | SAR 7",
  "Timely SAR 7s & RRRs | 3. The total number of timely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed ineligible | RRR",
  "Untimely SAR 7s & RRRs | 4. The total number of untimely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed eligible with no loss of benefits | SAR 7",
  "Untimely SAR 7s & RRRs | 4. The total number of untimely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed eligible with no loss of benefits | RRR",
  "Untimely SAR 7s & RRRs | 5. The total number of untimely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed ineligible | SAR 7",
  "Untimely SAR 7s & RRRs | 5. The total number of untimely SAR 7s & RRRs received from households within the Data Cohort Month that were disposed and subsequently deemed ineligible | RRR",
  "Late SAR 7s & RRRs | 6. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed and deemed eligible and experienced either no loss or loss of benefits. | SAR 7",
  "Late SAR 7s & RRRs | 6. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed and deemed eligible and experienced either no loss or loss of benefits. | RRR",
  "Late SAR 7s & RRRs | 6a. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed, deemed eligible and experienced no loss of benefits. | SAR 7",
  "Late SAR 7s & RRRs | 6a. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed, deemed eligible and experienced no loss of benefits. | RRR",
  "Late SAR 7s & RRRs | 6b.The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed, deemed eligible and experienced a loss of benefits. (This includes prorated applications) | SAR 7",
  "Late SAR 7s & RRRs | 6b.The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed, deemed eligible and experienced a loss of benefits. (This includes prorated applications) | RRR",
  "Late SAR 7s & RRRs | 7. The average number of days where benefits were lost due to late SAR 7 & RRR submission and the household experienced a loss of benefits within the First Month Following Data Cohort Month | SAR 7",
  "Late SAR 7s & RRRs | 7. The average number of days where benefits were lost due to late SAR 7 & RRR submission and the household experienced a loss of benefits within the First Month Following Data Cohort Month | RRR",
  "Late SAR 7s & RRRs | 8. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed and subsequently deemed ineligible | SAR 7",
  "Late SAR 7s & RRRs | 8. The total number of late SAR 7s & RRRs received from households within the First Month Following Data Cohort Month that were disposed and subsequently deemed ineligible | RRR",
  "SAR 7s & RRRs Not Renewed | 9. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the First Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 9. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the First Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 10. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the First Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 10. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the First Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 11. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Second Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 11. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Second Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 12. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Second Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits. | SAR 7",
  "SAR 7s & RRRs Not Renewed | 12. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Second Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits. | RRR",
  "SAR 7s & RRRs Not Renewed | 13. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Third Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 13. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Third Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 14. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Third Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 14. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Third Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 15. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Fourth Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 15. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Fourth Month Following Data Cohort Month were disposed and subsequently deemed eligible for benefits | RRR",
  "SAR 7s & RRRs Not Renewed | 16. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Fourth Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | SAR 7",
  "SAR 7s & RRRs Not Renewed | 16. The total number of SAR 7 & RRR households who do not renew in the Data Cohort Month, but submit a new application in the Fourth Month Following Data Cohort Month were disposed and subsequently deemed ineligible (include withdrawals) for benefits | RRR",
  "All CalFresh applications disposed of during the Data Cohort Month | 17. The total number of CalFresh and CFAP applications disposed of during the Data Cohort Month",
  "All CalFresh applications disposed of during the Data Cohort Month | 18. The total number of CalFresh and CFAP applications disposed of during the Data Cohort Month from a household who participated in CalFresh/CFAP within the prior four full calendar months",
  "Total applications from households with a recent (Within the Prior Four Full Calendar Months) SAR 7 or RRR | 19. The total number of CalFresh and CFAP applications disposed of during the Data Cohort Month from a household who had a SAR 7 or RRR due within the prior four full calendar months | SAR 7",
  "Total applications from households with a recent (Within the Prior Four Full Calendar Months) SAR 7 or RRR | 19. The total number of CalFresh and CFAP applications disposed of during the Data Cohort Month from a household who had a SAR 7 or RRR due within the prior four full calendar months | RRR",
  "Denied Applications with recent SAR 7 or RRR-related restoration | 20. The total number of denied CalFresh and CFAP applications disposed of during the Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was restored in the First Month Prior to Data Cohort Month | SAR 7",
  "Denied Applications with recent SAR 7 or RRR-related restoration | 20. The total number of denied CalFresh and CFAP applications disposed of during the Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was restored in the First Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (First Month Prior to Data Cohort Month) | 21. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the First Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (First Month Prior to Data Cohort Month) | 21. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the First Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (First Month Prior to Data Cohort Month) | 22. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the First Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (First Month Prior to Data Cohort Month) | 22. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the First Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Second Month Prior to Data Cohort Month) | 23. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Second Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Second Month Prior to Data Cohort Month) | 23. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Second Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Second Month Prior to Data Cohort Month) | 24. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Second Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Second Month Prior to Data Cohort Month) | 24. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Second Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Third Month Prior to Data Cohort Month) | 25. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Third Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Third Month Prior to Data Cohort Month) | 25. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Third Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Third Month Prior to Data Cohort Month) | 26. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Third Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Third Month Prior to Data Cohort Month) | 26. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Third Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Fourth Month Prior to Data Cohort Month) | 27. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Fourth Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Fourth Month Prior to Data Cohort Month) | 27. The total number of denied CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Fourth Month Prior to Data Cohort Month | RRR",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Fourth Month Prior to Data Cohort Month) | 28. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Fourth Month Prior to Data Cohort Month | SAR 7",
  "Applications with recent SAR 7 or RRR correlated discontinuation (Fourth Month Prior to Data Cohort Month) | 28. The total number of approved CalFresh and CFAP applications disposed of during Data Cohort Month from a household who was required to submit a SAR 7 or RRR and whose case was closed/discontinued in the Fourth Month Prior to Data Cohort Month | RRR",
  "Initial Applications with Expedited Service | 29. The average number of days to approval of initial CalFresh and CFAP applications with expedited service from the date of application or date of discovery, if applicable",
  "Initial Applications with Expedited Service | 30. The total number of initial applications with expedited service approved within one to three days",
  "Initial Applications with Expedited Service | 31. The total number of initial applications with expedited service approved within four to seven days",
  "Initial Applications with Expedited Service | 32. The total number of initial applications with expedited service approved after seven days",
  "Initial Applications with Non-Expedited Service | 33. The average number of days to approval of initial CalFresh and CFAP applications with non-expedited service from the date of application",
  "Initial Applications with Non-Expedited Service | 34. The total number of initial applications non-expedited service approved within one to seven days",
  "Initial Applications with Non-Expedited Service | 35. The total number of initial applications with non-expedited service approved within eight to fifteen days",
  "Initial Applications with Non-Expedited Service | 36. The total number of initial applications with non-expedited service approved within sixteen to twenty-two days",
  "Initial Applications with Non-Expedited Service | 37. The total number of initial applications with non-expedited service approved within twenty-three to thirty days",
  "Initial Applications with Non-Expedited Service | 38. The total number of initial applications with non-expedited service approved over thirty days"
];
// Added 2026-07-16: the pre-FY2020-21 CF296 report used a completely different tab
// ('FinalData', not 'Data_External') with fewer metrics (123 cells, not 135) and no
// County Code / Report Month columns. Rather than force-fit it into the current
// 135-column schema (which would leave 12 columns permanently blank and require
// guessing which legacy item maps to which current one), this era's data lives in
// its own CF296_Legacy tab with its own honest column count. See README.md.
var CF296_LABELS_LEGACY = [
  "A. APPLICATIONS FOR CALFRESH | 1. Applications received during the month | Total",
  "A. APPLICATIONS FOR CALFRESH | 1A. Online applications received during the month | Total",
  "A. APPLICATIONS FOR CALFRESH | 2. Applications disposed of during the month | Total",
  "A. APPLICATIONS FOR CALFRESH | 2A. Applications approved | Total",
  "A. APPLICATIONS FOR CALFRESH | 2A.1) Applications approved in over 30 days | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2A.1) Applications approved in over 30 days | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2A.1) Applications approved in over 30 days | C. Total",
  "A. APPLICATIONS FOR CALFRESH | 2B. Applications denied (Item 2B1 plus Item 2B2) | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2B. Applications denied (Item 2B1 plus Item 2B2) | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2B. Applications denied (Item 2B1 plus Item 2B2) | C. Total",
  "A. APPLICATIONS FOR CALFRESH | 2B.1) Applications denied because determined ineligible | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.1) Applications denied because determined ineligible | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.1) Applications denied because determined ineligible | C. Total",
  "A. APPLICATIONS FOR CALFRESH | 2B.2) Applications denied for procedural reasons | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.2) Applications denied for procedural reasons | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.2) Applications denied for procedural reasons | C. Total",
  "A. APPLICATIONS FOR CALFRESH | 2B.3) Applications denied in over 30 days | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.3) Applications denied in over 30 days | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2B.3) Applications denied in over 30 days | C. Total",
  "A. APPLICATIONS FOR CALFRESH | 2C. Applications withdrawn | A. PACF",
  "A. APPLICATIONS FOR CALFRESH | 2C. Applications withdrawn | B. NACF",
  "A. APPLICATIONS FOR CALFRESH | 2C. Applications withdrawn | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under expedited services | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under expedited services | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3. Of the applications disposed of during the month in Item 2, applications processed under expedited services | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A. Found entitled to expedited services | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A. Found entitled to expedited services | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A. Found entitled to expedited services | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.1) Benefits issued in 1 to 3 days | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.1) Benefits issued in 1 to 3 days | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.1) Benefits issued in 1 to 3 days | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.2) Benefits issued in 4 to 7 days | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.2) Benefits issued in 4 to 7 days | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.2) Benefits issued in 4 to 7 days | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.3) Benefits issued in over 7 days | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.3) Benefits issued in over 7 days | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3A.3) Benefits issued in over 7 days | C. Total",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3B. Found not entitled to expedited services | A. PACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3B. Found not entitled to expedited services | B. NACF",
  "B. APPLICATIONS PROCESSED UNDER EXPEDITED SERVICES (ES) | 3B. Found not entitled to expedited services | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4. Cases brought forward at the beginning of the month | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 4A. Item 8 from last month's report, as reported to CDSS | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4A. Item 8 from last month's report, as reported to CDSS | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4A. Item 8 from last month's report, as reported to CDSS | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 4B. Adjustment | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4B. Adjustment | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 4B. Adjustment | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5. Cases added during the month | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | PACF (Federal)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | PACF (Federal/State)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | PACF (State)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | NACF (Federal)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | NACF (Federal/State)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | NACF (State)",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5A. Applications Approved | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5B. Change in asssistance status from PACF or NACF | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5B. Change in asssistance status from PACF or NACF | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5B. Change in asssistance status from PACF or NACF | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5C. Inter-County Transfers | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5C. Inter-County Transfers | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5C. Inter-County Transfers | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5D. Cases with eligibility reinstated and benefits pro-rated during the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5D. Cases with eligibility reinstated and benefits pro-rated during the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5D. Cases with eligibility reinstated and benefits pro-rated during the month | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 5E. Other Approvals | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5E. Other Approvals | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 5E. Other Approvals | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6. Total cases open during the month | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 6A. Pure federal cases | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6A. Pure federal cases | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6A. Pure federal cases | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 6A.1) Federal persons in Item 6A cases plus federal persons in Item 6B cases | Federal Persons",
  "C. CERTIFIED CASELOAD MOVEMENT | 6B. Federal/State combined cases | State Persons: Single",
  "C. CERTIFIED CASELOAD MOVEMENT | 6B. Federal/State combined cases | State Persons: Families",
  "C. CERTIFIED CASELOAD MOVEMENT | 6B. Federal/State combined cases | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6B. Federal/State combined cases | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6B. Federal/State combined cases | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 6C. Pure state cases | State Persons: Single",
  "C. CERTIFIED CASELOAD MOVEMENT | 6C. Pure state cases | State Persons: Families",
  "C. CERTIFIED CASELOAD MOVEMENT | 6C. Pure state cases | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6C. Pure state cases | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 6C. Pure state cases | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 7. Cases discontinued during the month | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 7A. Households discontinued due to recipient failure to complete application process for ongoing benefits (Expedited services only) | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 7A. Households discontinued due to recipient failure to complete application process for ongoing benefits (Expedited services only) | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 7A. Households discontinued due to recipient failure to complete application process for ongoing benefits (Expedited services only) | C. Total",
  "C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | A. PACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | B. NACF",
  "C. CERTIFIED CASELOAD MOVEMENT | 8. Cases brought forward at the end of the month | C. Total",
  "D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | A. PACF",
  "D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | B. NACF",
  "D. RECERTIFICATIONS | 9. Recertifications disposed of during the month | C. Total",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | PACF: Federal",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | PACF: Federal/State",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | PACF: State",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | NACF: Federal",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | NACF: Federal/State",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | NACF: State",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | A. PACF",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | B. NACF",
  "D. RECERTIFICATIONS | 9A. Determined continuing eligible | C. Total",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | PACF: Federal",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | PACF: Federal/State",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | PACF: State",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | NACF: Federal",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | NACF: Federal/State",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | NACF: State",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | A. PACF",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | B. NACF",
  "D. RECERTIFICATIONS | 9B. Determined ineligible | C. Total",
  "D. RECERTIFICATIONS | 10. Overdue recertifications during the month | A. PACF",
  "D. RECERTIFICATIONS | 10. Overdue recertifications during the month | B. NACF",
  "D. RECERTIFICATIONS | 10. Overdue recertifications during the month | C. Total"
];